### ISSUE TITLE
Sprint 3: Enabler - preflight

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#56]
Investigate the below reported error.

Reference - testing results from @Filip3mac ([#307](https://github.com/keitaroinc/getafix_internal-getafix-tasks/issues/307)):

 _When i run enabler preflight it errors on istioctl saying that i am running an old version but i am running the latest 1.20.1_

[filip@Thinkpad enabler (⎈ |kind-kind:default)]$ istioctl version
no ready Istio pods in "istio-system"
1.20.1
[filip@Thinkpad enabler (⎈ |kind-kind:default)]$ enabler preflight
✓ java jdk 11
✓ docker
✓ helm 3
✓ kind
✓ skaffold
✓ kubectl
**error: Old version of istio detected when running "istioctl" from PATH.**

**Comment by teodora-aleksovska** [comment]
Result after running enabler preflight:

teodora@teodora-ThinkPad-T16-Gen-1:~/.config/enabler$ enabler preflight 
✓ java jdk 11
✓ docker
✓ helm 3
✓ kind
✓ skaffold
✓ kubectl
✓ istioctl


Please check .tools-version file and check if versions are compatible before running enabler preflight command. 

This issue is fixed with setup init.

**Comment by JasminaPN** [comment]
closing as fixed.
